/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_retrylife_libvec2_Vector3JNI */

#ifndef _Included_ca_retrylife_libvec2_Vector3JNI
#define _Included_ca_retrylife_libvec2_Vector3JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_retrylife_libvec2_Vector3JNI
 * Method:    length
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ca_retrylife_libvec2_Vector3JNI_length
  (JNIEnv *, jobject);

/*
 * Class:     ca_retrylife_libvec2_Vector3JNI
 * Method:    norm
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ca_retrylife_libvec2_Vector3JNI_norm
  (JNIEnv *, jobject);

/*
 * Class:     ca_retrylife_libvec2_Vector3JNI
 * Method:    dot
 * Signature: (Lca/retrylife/libvec2/Vector3JNI;)D
 */
JNIEXPORT jdouble JNICALL Java_ca_retrylife_libvec2_Vector3JNI_dot
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
